V2 background color continuity across all pages #1200
hackforla/311-data pull request #1274
Opened 2022-07-07 21:50 UTC by ardada2468

Fixes #1200 

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

2022-07-07 23:02 UTC, nichhk requested changes
Could you also share some screenshots showing the color change? Thanks!

2022-07-07 23:02 UTC, nichhk commented on client/theme/theme.js
> +      default: '#0f181f',
It looks like we generally use uppercase for color codes, so let's stick with that for consistency.

2022-07-16 15:50 UTC, ardada2468 commented
![image](https://user-images.githubusercontent.com/37542991/179362075-07685d53-c378-4fdf-9f46-fa9d7d231618.png)


This is how it looks on my end.

2022-07-19 20:24 UTC, nichhk approved these changes
LGTM! Thanks Arnav!

2022-07-22 23:33 UTC, merged