1308 fe preventing dates longer than 3 months
hackforla/311-data pull request #1342
Opened 2022-09-07 23:58 UTC by jekijo

Fixes #{1308}

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

While still able to click on and select dates outside of the available range when using the disabledDays arg, they are now greyed out and return no data when selected.

2022-09-08 03:13 UTC, nichhk requested changes
Looks great, thanks!

Could you attach a screenshot showing how the calendar looks now?

2022-09-08 03:13 UTC, nichhk commented on server/api/code/lacity_data_api/models/service_request.py
> +@cached(alias="default")
Please delete this change from the PR

2022-09-09 02:44 UTC, jekijo commented
<img width="642" alt="Screen Shot 2022-09-08 at 7 41 57 PM" src="https://user-images.githubusercontent.com/88257653/189261424-c49b2acf-ca3f-4bb3-b888-b3342bcc266b.png">
<img width="662" alt="Screen Shot 2022-09-08 at 7 42 22 PM" src="https://user-images.githubusercontent.com/88257653/189261454-129829c3-af2d-46bf-92d2-e0764bf4624d.png">
<img width="658" alt="Screen Shot 2022-09-08 at 7 42 45 PM" src="https://user-images.githubusercontent.com/88257653/189261465-9227251d-78b5-4c20-90ad-d745dd0aa0de.png">

2022-09-09 18:15 UTC, nichhk requested changes
Thanks for the screenshots! Looks great. I left another comment on a comment from the first round that might've been missed.

2022-09-09 18:15 UTC, nichhk commented on server/api/code/lacity_data_api/models/service_request.py
> +@cached(alias="default")
Friendly ping

2022-09-09 21:11 UTC, nichhk approved these changes
Looks great, thanks Killen! Feel free to merge when you are ready.

2022-09-12 17:48 UTC, merged

2022-09-28 22:38 UTC, melissahermes99 commented
It's looking great! Would it be possible to cut the calendar length to align with the line on the dropdown? The calendar color also might blend in too much with the rest of the menu. I also just realized that we no longer have a view charts button on the map menu. I'm not sure if we did that intentionally. Let me run that by Elizabeth to confirm that decision and ask her thoughts on the calendar color.

2022-09-29 02:41 UTC, melissahermes99 commented
![image](https://user-images.githubusercontent.com/97048386/192926432-ef437b66-35c3-4cf5-8ce9-ae7eeb618c5a.png)
Would this be possible to create?