added name and message validations
hackforla/311-data pull request #1438
Opened 2023-01-24 03:20 UTC by chencc33

Fixes #{issue number here}

  - [ ] Up to date with `dev` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

2023-01-26 05:28 UTC, edwinjue requested changes

2023-01-26 05:28 UTC, edwinjue commented on client/components/contact/ContactForm.jsx
> +      && !noMessage && invalidMessageLength) {
should this be !invalidMessageLength?

2023-02-01 19:08 UTC, chencc33 commented on client/components/contact/ContactForm.jsx
> +      && !noMessage && invalidMessageLength) {
Thanks! I have updated the code.

2023-02-02 07:33 UTC, edwinjue approved these changes
Awesome, looks good! Feel free to merge

2023-02-08 21:48 UTC, merged