Added Accesible Menu dropdown
hackforla/311-data pull request #1614
Opened 2023-11-05 18:42 UTC by funbunch

Fixes #{1458}

  - [x] Up to date with `dev` branch
  - [x] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

2023-11-05 18:45 UTC, funbunch commented
Updated li menu with Privacy heading taken out and new dropdown added. 
<img width="547" alt="Screenshot 2023-11-05 at 10 43 43 AM" src="https://github.com/hackforla/311-data/assets/3441200/41a275a1-0d02-4ac6-b38f-75e69dfb35a2">

2024-01-11 05:12 UTC, edwinjue commented
Hi @annaseulgi, can you compare this screenshot of the Accessibility Info Menu to the latest version in your Figma design to let me know if this looks good to proceed. Thanks

![image](https://github.com/hackforla/311-data/assets/1448719/9c8d8cef-a42b-40c7-aa9c-d666ac265352)

2024-01-12 00:45 UTC, annaseulgi commented
@edwinjue @funbunch Looks great! Ideally, the modal should hug the right side of the window (if possible). Additionally, please add a space in front of each bolded word after the description of an action (ex. Select buttons: Spacebar). Currently, it looks too close together (ex above. Select buttons:Spacebar).

Image below for reference from the mock-up:

![Screen Shot 2024-01-11 at 4 42 11 PM](https://github.com/hackforla/311-data/assets/140572118/c4361a49-f367-4767-9e25-cbde17a32b3f)

2024-01-12 03:01 UTC, funbunch commented
Thanks @annaseulgi. Will try to update these!

2024-01-18 00:14 UTC, funbunch commented
@annaseulgi @edwinjue Fixed the text space issue. The positioning of the modal is something we might have to research further later on. This was committed on the #1458 branch.

<img width="443" alt="Screenshot 2024-01-17 at 4 10 45 PM" src="https://github.com/hackforla/311-data/assets/3441200/965b15f2-e55d-4ca0-9469-bd82dbf4aed6">

2024-01-26 22:58 UTC, ryanfchase commented
@funbunch I'm really confused on what could be going on with the commits on this branch. It seems to be including commits from `main` when it should be ignoring them. Any idea why it is showing up like that?

I made a branch based on `1458-header-update-requests` and it doesn't include the commits from other devs: https://github.com/hackforla/311-data/compare/main...temp-ryan-branch-should-delete-asap?expand=1

Perhaps you should run `git pull` on your branch -- this will add a merge commit but I think that won't be an issue.

2024-01-27 21:47 UTC, funbunch commented
We fixed the files changed issue and this is ready for review.

2024-01-30 02:18 UTC, ryanfchase commented on components/Header.jsx
> +        {/* <Button
I actually think we're ok to completely remove this. When Dashboard gets reintroduced, it's unlikely we'll keep the implementation that we're seeing here

2024-01-30 02:19 UTC, ryanfchase commented on components/Header.jsx
> +  const [isDashboardOpen, setIsDashboardOpen] = React.useState(false);
Let's get rid of the dashboard navbar state since we aren't planning on utilizing it until post-launch

2024-01-30 02:20 UTC, ryanfchase commented on Routes.jsx
> +// import DashboardOverview from '@dashboards/DashboardOverview';
Let's remove unused imports

2024-01-30 02:20 UTC, ryanfchase commented on Routes.jsx
> +              {/* <Route path="/dashboard-overview" element={<DashboardOverview />} />
Let's remove the unused Routes (including "/dashboard-comparison" just below)

2024-01-30 02:21 UTC, ryanfchase commented on components/Header.jsx
> +  // iconStyle: {
Let's leave this out, thanks!

2024-01-31 03:25 UTC, funbunch commented
@ryanfchase Pushed these changes!

2024-01-31 19:46 UTC, ryanfchase requested changes
@funbunch I think the `getContentAnchor` prop in the `Menu` component is causing an error at runtime. Can we get this resolved? TY!

<details><summary>Image of error</summary>
<p>

![image](https://github.com/hackforla/311-data/assets/6414668/34cae98e-4f02-43b5-b6c2-ae08b1aa8ac7)


</p>
</details>

2024-02-01 00:21 UTC, funbunch commented
@ryanfchase Updated to correct that warning. Let's try again.

2024-02-01 00:43 UTC, merged