Fix AcknowledgeModal to only show on initial load
hackforla/311-data pull request #1709
Opened 2024-04-16 05:24 UTC by drakenguyen4000

Fixes #1707

### What changes did you make?
- Add a new state to `MapContainer` to track if the `AcknowledgeModal` has been shown.
- Update the ternary to render the AcknowledgeModal only if the data is done loading.  
- Update `AcknowledgeModal` to accept a callback prop for closing.
 
### Why did you make the changes (we will use this info to test)?
  - To ensured that AcknowledgeModal is displayed only once upon the initial load of the application and does not reappear after subsequent data load or filter updates, so that users can have more smooth interaction with the map.
  
  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved
Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

2024-04-16 19:44 UTC, Skydodle requested changes
The conditional rendering is placed at the wrong line. We DO want the `LoadingModal` & `FunFactModal` whenever the db is loading or map is loading, regardless of whether it's intial load or later during user navigation.

The goal of this issue to restrict `AcknowledgeModal` to only show up during initial load.

Please help moving the flag checking  condition to the correct line.

2024-04-16 19:44 UTC, Skydodle commented on components/Map/index.js
> +        {(isDbLoading || isMapLoading) && acknowledgeModalShown === false ? (
This actually disable the `LoadingModal` and `FunFactModal` after the initiial load, which is not what we want. Our goal is to disable `AcknowledgeModal` if it already has been rendered once on initial load.

We should leave line 403 as it was: 
```
{(isDbLoading || isMapLoading) ? (
```

2024-04-16 19:44 UTC, Skydodle commented on components/Map/index.js
> +          <AcknowledgeModal onClose={this.onClose}/>
the condition `acknowledgeModalShown` should be place here at line 408 to conditionally render the `AcknowledgeModal`.

```
        ) : !acknowledgeModalShown ? (
          <AcknowledgeModal onClose={this.onClose}/>
        ) : null}
```

2024-04-17 04:53 UTC, drakenguyen4000 commented
@Skydodle Okay, I mean the changes necessary so the AcknowledgeModal only shows up the first time and not after.

2024-04-17 20:51 UTC, sophia-bui approved these changes
Nice work! The acknowledgement modal now displays only once on the initial load. I tested this for several random date ranges throughout the year. The loading modal and fun fact modal still appears on each search if the data/map needs to load.

2024-04-18 03:02 UTC, Skydodle approved these changes
Pulled down the revised PR for review. The `AcknowledgeModal` is conditionally rendered correctly in test, and code looks good. Thanks @drakenguyen4000 !

2024-04-19 04:50 UTC, merged