1666 pull data from previous years
hackforla/311-data pull request #1711
Opened 2024-04-17 02:16 UTC by Skydodle

Fixes #1666 

### Pre-Merge Checklist

  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

### Changes Made

- Transfer the 2023 parquet file from old HuggingFace (Edwin's personal) to 311 Data's HuggingFace 2023 repo
- Set up dataset parquet file URL pointers and file path registrations in `DbProvider`
- Re-enable UI calendar to browse back to 2023 in `ReactDayPicker`
- Extract current calendar date year from Redux `startDate` prop, use it to dynamically query parquet file name by year as well as create db table by year
- Uplift dynamic table name generation logic to `DbProvider` as a DbContext prop, so that it can be access both in `MapContainer` and `RequestDetail` and also accessible anywhere that requires this table name in the codebase.

### Bug Fixed at Testing
- Bug Fix: Update the query table name to current year in the Footer's `LastUpdated` component, kept it static for now
- Bug Fix: Update the query table name to the dynamic table name context prop in `RequestDetail`

### More Info

2023 data is now available for browsing on the UI in this PR. This ticket was a prototype to see if our solution would work. Now that it works, Ryan will create a new ticket to apply the same data flow for the rest of the previous years, ie. 2016 to 2022.

2024-04-17 20:39 UTC, sophia-bui approved these changes
This looks great! Dates from January 2023 and beyond appear, loading modal appears. I see the appropriate changes in the queries, DbProvider, and hugging face URL transferred. 

Excited to see this solution applied in the other use cases. Approving in case it is still needed.

2024-04-27 20:14 UTC, ryanfchase commented
@Skydodle This is looking really good! I have one area that might need an adjustment.

If you attempt to specify a date range that starts in 2023 and ends in 2024, we only get data from 2023. I'm assuming that's because we are making a query on the 2023 table where there is no 2024 data present.

I think we could handle this in a number of different ways (e.g. write 2 queries for each table, combine the tables into 1, or even restrict user from picking data that spans 2 years). What's everyone's thoughts on how to proceed?

cc @sophia-bui since you're caught up on this PR

2024-04-27 20:15 UTC, ryanfchase requested changes
Requesting changes, but open to deferring work to an upcoming ticket.

https://github.com/hackforla/311-data/pull/1711#issuecomment-2081170326

2024-04-30 01:34 UTC, Skydodle commented
@ryanfchase Thanks so much for spotting this bug! I was hoping the reviews would find bugs that I overlooked. The changes affects many components that I really appreciate the extra pairs of eyes.

I've came up with a initial working solution. The idea is that we conditionally query for data based on the search range. If search range is within same year, we query only that year's table for data. Otherwise if search range start date and end date have two different years, we query both years' tables and union them.

The same logic would be applied to the pin details in `RequestDetail.jsx`.

I'm going to take some more time to look for room for improvement before pushing.

2024-05-03 20:37 UTC, Skydodle commented
@ryanfchase I've pushed the fix for handling cross-year date range with comment explanation. Pleas kindly review at your convenience. Thank you!

2024-05-08 21:58 UTC, ryanfchase approved these changes
Good improvements! Tested and confirmed it fixes the aforementioned bug

2024-05-09 00:56 UTC, Skydodle commented
@ryanfchase per our discussion in prepartion for #1716, I added time performance console logs in new commit.

2024-05-09 00:57 UTC, ryanfchase approved these changes
new logs approved

2024-05-09 00:58 UTC, merged