modify fun fact list to approved fact list
hackforla/311-data pull request #1743
Opened 2024-06-01 04:43 UTC by drakenguyen4000

Fixes #1727
  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

**Changes**
Updated fact list in data/fact.js to match the facts provided in word document.

2024-06-01 22:51 UTC, Skydodle submitted a review, later dismissed
Pulled down and tested, all new fun facts show up in the cycle as expected. Looks good to me!

2024-06-01 22:51 UTC, Skydodle commented on data/facts.js
> +  'Neighborhood Councils receive $32,000 annually in public funds. These funds support community events, programs, and advocacy initiatives, addressing issues such as infrastructure, public safety, a
This should be with a '$' sign as '$29497.15'. The rest looks good to me. Pulled down and tested, all the new fun facts showed up as expected.

2024-06-01 23:02 UTC, Skydodle approved these changes

2024-06-03 17:01 UTC, ryanfchase requested changes
@drakenguyen4000 Can you remove the extra spaces after some of these modified lines? And on lines 15-17 as well?

2024-06-06 18:00 UTC, ryanfchase approved these changes
Latest changes look good, approving

2024-06-07 04:49 UTC, merged