1746 Add SR CSV download for Address and Count
hackforla/311-data pull request #1752
Opened 2024-06-08 01:08 UTC by kdow

Fixes #[1746](https://github.com/hackforla/311-data/issues/1746)

### Notes:
- I had to change the table from requests to requests_2024 for the queries to work. Should this be left as requests or requests_2024 for now?
- This implementation will only generate the SR count CSV if it meets the following conditions: exactly one SR type is selected, a NC is selected, and status is Open. Should any of those requirements be changed?
- I've verified that the CSV is generated in the specified conditions, along with NeighborhoodData.csv that was previously implemented

  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

Any questions? See the [getting started guide](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md)

2024-06-08 23:57 UTC, Skydodle commented
Hi @kdow, welcome and thanks for your hard work!

I'm addressing the question regarding the table name querying:

**Background**
Up until the last couple of months, our app was only able to display current year's data, which is why the older files like `ExportButton.jsx` have a static table name like `requests` because we only need 2024 year's data at the time. We recently restructured our data setup and integrated the ability to display multiple years, and table names are now dynamically generated by year: ie. `` `requests_${year}` `` such as `request_2024` table contains 2024 data, `request_2023` table contains 2023 data etc.

**Dynamic Queries**
We want the user to be able to export data based on the date ranges they selected on the UI calendar, therefore it's not ideal to hardcode the table name to query only the `requests_2024` table. Instead we should make the table name in the query dynamic  as `` `requests_${year}` `` based on the user's currently selected start date and end date. We can extract the start date year and end date year from the redux props `filters.startDate` and `filters.endDate`, which are also dynamic and updates whenever the user changes the date range selection on the UI calendar.

Year extraction implementations can be found in `components/Map/index.js` using the `Moment.js` library specifically in the `getAllRequests` function.

**Consider Cross-Year Dates**
Since our data tables are segregated by year, the query logic needs to consider when the user selects different years in startDate and endDate. This has also been implemented in `getAllRequests` in `components/Map/index.js` since we encountered this issue as a bug previously.
Here is the text explanation on the logic: https://github.com/hackforla/311-data/pull/1711#issuecomment-2093729474

**Extra Info**
- If you want to dig into how data flows from source into DuckDB, check out `components/db/DbProvider.jsx`
- For how DuckDB create the data tables, check out `createRequestsTable` in `components/Map/index.js`

I hope this explanation helps. Please let me know if you have any questions, I'd be happy to help!

2024-06-09 00:05 UTC, kdow commented
That does help, thanks for the thorough explanation! I'll make that change in a revision today or tomorrow.

2024-06-10 00:51 UTC, kdow commented on .github/ISSUE_TEMPLATE/blank_epic.md
Disregard this file - it's from changes merged from main since my first commit

2024-06-11 01:39 UTC, ryanfchase requested changes

2024-06-11 01:39 UTC, ryanfchase commented on components/main/Desktop/ExportButton.jsx
> +    const generateQuery = (grouped = false) => {
I like that you've abstracted the logic for generating these query strings into its own function. I'm wondering if we can improve readability by additionally making a few helper functions like so...

```js
const groupRequestsByAddress(year, startDate, endDate, councilId, types) => 
  `SELECT Address, COUNT(*) AS NumberOfRequests FROM requests_${year}
  WHERE CreatedDate >= '${startDate}' 
  AND CreatedDate < '${endDate}' 
  AND Status = 'Open' 
  AND NC = '${councilId}' 
  AND RequestType IN (${types})
  GROUP BY Address`;
```

```js
const getAllRequests(year, startDate, endDate, types, status='', councilId='') =>
 `SELECT * FROM requests_${year} 
  WHERE CreatedDate >= '${startDate}' 
  AND CreatedDate < '${endDate}'
  ${requestStatusFilter !== '' ? ` AND Status='${status}'` : ''}
  ${filters.councilId !== null ? ` AND NC='${councilId}'` : ''} 
  AND RequestType IN (${types});`;
```

This should simplify the logic of `generateQuery()`. I imagine that the queries that require `UNION_ALL` can look like this:

```js
if (grouped) {
  return `(
    ${groupRequestsByAddress(startYear, filters.startDate, endofStartYear, filters.councilId, types)}
  ) 
  UNION ALL (
    ${groupRequestsByAddress(endYear, startOfEndYear, filters.endDate, filters.councilId, types}
  )
}
// do the same for getAllRequests()
```

2024-06-11 01:39 UTC, ryanfchase commented on components/main/Desktop/ExportButton.jsx
> +        return `SELECT * FROM requests_${startYear}
I would either convert this logic block to explicitly be if-else, so readers  can see `startYear === endYear` and `grouped` are the deciding factors between which logical pathway is taken. OR I would add comments indicating what the state of logic should be...
i.e. here on line 66: `//here, our data comes from the same year and we wish to obtain all rows that match the filters

2024-06-11 01:41 UTC, ryanfchase commented on components/main/Desktop/ExportButton.jsx
> +        return `SELECT * FROM requests_${startYear}
While we're considering comments, here's my other request for adding a note: https://github.com/hackforla/311-data/issues/1746#issuecomment-2159607947

2024-06-15 02:56 UTC, Skydodle commented
Hi @kdow, just wanna let you know that I didn't forget about reviewing this PR. I'm just waiting to see what you think about Ryan's requested changes. Thanks.

2024-06-15 17:56 UTC, kdow commented on .github/ISSUE_TEMPLATE/blank_epic.md
I was able to merge another newer commit from main without it adding but I wasn't able to push my changes without pulling from my branch first and it got added in. I can try fixing it again in another commit or closing this PR and opening a new one.

2024-06-15 19:07 UTC, ryanfchase commented on .github/ISSUE_TEMPLATE/blank_epic.md
Yeah, so sorry about all that. I was using github to create a new template and didn't quite see the harm in pushing directly to main. I'll just stick to the usual process to avoid this in the future.

2024-06-15 19:48 UTC, ryanfchase commented on .github/ISSUE_TEMPLATE/blank_epic.md
I think one last option would be for you to run `git rebase main` and resolve the merge conflicts by accepting the current changes (aka choosing your changes each time). Let me confirm this by running it locally to see if it prunes out that extra commit.

2024-06-15 19:59 UTC, ryanfchase commented on .github/ISSUE_TEMPLATE/blank_epic.md
Ok I've attempted it on a branch that derives from your branch....
1. on branch `main` run `git pull`
2. switch to your branch, `1746-sr-csv-download-address-count`
3. run `git rebase main`
4. There will be a first merge conflict
  - address it by accepting all instances of _your_ changes
  - save the file
  - Run `git add .` to keep those changes
  - Run `git rebase --continue`
5. There will be a second merge conflict
  - repeat steps above
6. You might get a warning about "The previous cherry-pick is now empty..."
  - you can run  `git rebase --skip` to conclude the rebase
7. Run `git push`
8. You'll see that you only have a few commits, since we've pruned my commit, plus a couple of your repeat commits/merges

Here's my end result on a demo PR: https://github.com/hackforla/311-data/pull/1766

2024-06-19 20:48 UTC, Skydodle requested changes
@kdow Thanks for your great work on parameterizing the query table name.

Pulled down the PR and tested locally. I uncommented the `ExportButton` in `FilterMenu.js` and downloaded the csv.

The columns that suppose to have date values in date format, such as `CreatedDate`, `UpdatedDate`, `ServiceDate`, and `ClosedDate` columns, appeared to be timestamps in milliseconds. See screenshot below:

<details><summary>Screenshot of downloaded csv</summary>
<p>

![Screenshot 2024-06-19 at 1 18 40 PM](https://github.com/hackforla/311-data/assets/69279538/02c59183-2689-4dc1-8738-1e4c10ba7e8c)


</p>
</details> 

In this example, the `CreatedDate` column for the first row value is `1718226384000`, which is timestamp (milliseconds since the Unix epoch) for `2024-06-12 21:06:24`.

We need to convert the timestamps into human-readable date format before exporting to CSV.

2024-06-19 20:48 UTC, Skydodle commented on components/main/Desktop/ExportButton.jsx
> +
I would do the timestamp-to-date conversion here before passing neighborhoodResults to `Papa.unparse`.

Something like
````javascript
const formattedResults = neighborhoodResults.map(row => ({
  ...row,
  CreatedDate: row.CreatedDate ? moment(row.CreatedDate).format('YYYY-MM-DD HH:mm:ss') : null,
  UpdatedDate: row.UpdatedDate ? moment(row.UpdatedDate).format('YYYY-MM-DD HH:mm:ss') : null,
  serviceDate: row.serviceDate ? moment(row.serviceDate).format('YYYY-MM-DD HH:mm:ss') : null,
}));
````

2024-06-19 20:48 UTC, Skydodle commented on components/main/Desktop/ExportButton.jsx
> +    if (!isEmpty(neighborhoodResults)) {
then pass `formattedResults` here instead of `neighborhoodResults`, same for Papa.unparse() below.

2024-06-19 20:49 UTC, Skydodle commented on components/main/Desktop/ExportButton.jsx
> +
Need to include ClosedDate column in there

2024-06-19 22:44 UTC, ryanfchase approved these changes
the PR is looking clean, and the final commit on formatting the date output in the csv looks good too. Approved.

2024-06-20 07:41 UTC, Skydodle commented
Hey Kelly, the formatted dates looks good to me! I want to approve this, but I encountered some weird issues during testing.
I'm not sure if the issue came from this PR or it's an existing bug on the application.

So I downloaded the CSVs from testing different date ranges. The recent dates in June looks good. 
However, when I do dates in May, March, Feb, and Jan, the number of rows in the CSV don't match the number of dots on the map. For example, I selected a district in date range say 1/5 to 1/20, visually on the map there are more than 20 dots in the district, but the downloaded CSV only has one row. 

Further more, some visually has multiple dots, but when I clicked 'export', a pop-up says "No 311 data available within the selected filter..." This is the part that makes me think that it might be an existing bug in the app, apart from this PR.

This was tested with several different districts and different ranges. And it seems to be more messed up the further back in time we go.

@ryanfchase What's your input on this? Continue investigation within this ticket or approve and create new bug ticket?

<details><summary>screentshots</summary>
<p>
<img width="1181" alt="Screenshot 2024-06-20 at 12 08 54 AM" src="https://github.com/hackforla/311-data/assets/69279538/42110ac9-b1fa-40a5-b240-c100e35c9a52">

![Screenshot 2024-06-20 at 12 09 20 AM](https://github.com/hackforla/311-data/assets/69279538/9607c22d-3337-48ee-b012-20989eca3dd5)

<img width="1052" alt="Screenshot 2024-06-20 at 12 14 13 AM" src="https://github.com/hackforla/311-data/assets/69279538/b171de1a-8f6d-49f1-8f25-e5d49f4ad0ce">


![Screenshot 2024-06-20 at 12 14 19 AM](https://github.com/hackforla/311-data/assets/69279538/a4e8c37b-113b-4fc1-a813-3ddb98bdb9f7)


<img width="1061" alt="Screenshot 2024-06-20 at 12 15 38 AM" src="https://github.com/hackforla/311-data/assets/69279538/e6761666-636e-4de7-bdde-729cb12c0e73">




</p>
</details>

2024-06-20 16:06 UTC, bphan002 commented
Availability for PR Review Friday 6/20/24

I looked at this briefly, but will need more time to look into it more on Friday. 

@ryanfchase  @Skydodle 
On a side note(Not sure if it is within the scope of this issue),  If a user selects a year in both 2023-2024, then only the 2023 data is exported out.

2024-06-22 06:35 UTC, bphan002 commented
@Skydodle. @kdow

I also got that alert message for some of the export request even though there should be data. I'll spend a bit more time to see what the issue may be.

Here are some side findings.
For the function getAllRequests, groupRequestsByAddress we needed to change AND Created Date < '${endDate}' to be <=
I think this may also contribute to the rows and pins not matching.


Even though there should be 5 rows I got 9.   I noticed there the same request has been created within a span of a couple of minutes so the data is overlapping.  I'm not sure if we want this filtered out in the future.

2024-06-22 07:18 UTC, bphan002 requested changes
Map Request Type to the exact string to see if that solves the issue

2024-06-24 22:50 UTC, kdow commented
Thanks all for helping to find and figure out some of these issues. I've updated the requestType names and createdBy end dates that were effecting the results.

I also found another issue after fixing those. Throughout the codebase we check for the SR status as 'Open' or 'Closed', but I've found there's also a status of 'Pending'. A lot of the results that were missing from the export but appeared in the browser had the 'Pending' status.

I'll submit an updated revision tonight or tomorrow with the fixes.

2024-06-24 23:35 UTC, ryanfchase commented
> Thanks all for helping to find and figure out some of these issues. I've updated the requestType names and createdBy end dates that were effecting the results.
> 
> I also found another issue after fixing those. Throughout the codebase we check for the SR status as 'Open' or 'Closed', but I've found there's also a status of 'Pending'. A lot of the results that were missing from the export but appeared in the browser had the 'Pending' status.
> 
> I'll submit an updated revision tonight or tomorrow with the fixes.

Thanks @kdow -- I've just made a comment with a link to this PR so that volunteers can easily access their comments if they need to. Feel free to continue your plan to make a new PR.

2024-06-26 16:54 UTC, Skydodle commented
Will complete review before Thurs 6/27 EOD

2024-06-26 19:39 UTC, bphan002 approved these changes
The date range now includes the last date and the csv now populates if the range involve multiple years.  Great job on these modifications.

Using the same test case

Boundaries United NEIGHBORHOODS NC
Date Range 06/14/2024 - 06/21/2024
Request Types Single Streetlight

The address 2336 S 4TH AVE, 90018 pin does not appear, but was included in the csv. I'm not sure what is going on, but everything else looks great.  I think another issue is needed in order to look into this. @ryanfchase @Skydodle 

Approving on the condition that another issue needs to be created for the pins not matching with the csv.  (Unless the issue is related to the code and I couldn't pinpoint it)

2024-06-26 20:01 UTC, kdow commented
I think the pin for 2334 S 4TH AVE, 90018 might be overlapping the pin for 2336 S 4TH AVE, 90018 and that's why we can't see it on the map but it's on the export. If that is the case, it would be ideal to have it viewable on the map in some way.

2024-06-28 04:46 UTC, Skydodle approved these changes
I checked on Google Map, 2334 S 4TH AVE and 2336 S 4TH AVE are actually in the same house same building. The request for 2336 was created before 2334 but on the same day. So it seem like in our pin rendering system, if different requests on the same date and on the same building, it will only render pin for the latest request. Or it could be overlapping as Kelly said, maybe it doesnt know how to display a second pin at a different spot on the same house.

I think this bug should be address in another ticket with our pin rendering logic and not part of this issue. Everything else looks good. Will go ahead and approve. Thank you so much for your hard work @kdow !

2024-06-28 19:23 UTC, merged