1759 restrict future date selection
hackforla/311-data pull request #1776
Opened 2024-06-20 00:48 UTC by bphan002

Fixes #1759

### Issue
Users can select past the current date and still have the page render data. 

### Changes

Date picker now shows a pop up error message if it is later than the current date. Map rendering will not occur if this is the case. There was no design guideline for the error message so I went with the default material UI error message.  Error message is displayed for 2 seconds.

![Screenshot 2024-06-19 at 5 41 32 PM](https://github.com/hackforla/311-data/assets/83096266/30032579-cf1b-4c3a-aa94-4c57e71a6d8f)

  - [ ] Up to date with `main` branch
  - [ ] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

2024-06-20 04:23 UTC, aqandrew requested changes
1. The error message popup causes a layout shift, which makes for a disruptive user experience:

   https://github.com/hackforla/311-data/assets/9038965/1ef9b91f-19f4-434a-9cef-a4a2dadacdc6

2. The above screen recording shows that if a future date is selected while a date range is selected, the end date gets deselected.

### Possible solution

I'm not sure if there is a suitable place in our UI for such an error message. But we can avoid these 2 problems altogether if we take a different approach to restricting future date selections. Imo it'd be a good idea to follow Google Flights' example, which simply makes past dates non-interactable:

https://github.com/hackforla/311-data/assets/9038965/fc33da6d-c261-45a0-9b59-74d509151666

In other words, no state changes occur if an invalid date is clicked. If we really want to be more explicit, we could also set `cursor: not-allowed` as a hover style for future dates.

What do you think @bberhane? / Was there any input from Design on this?

2024-06-20 06:48 UTC, Skydodle commented
Hi @bphan002, sorry I was gonna comment on this before you started working but totally forgot. I actually worked on React DayPicker previously on an issue very similar to this one, and there's a 4 lines solution for this issue that will do everything we wanted.

### Disable the future month navigation
React DayPicker actually has a built-in props for preventing future months navigation. Similar to PR #1686 where we restricted month navigation for unavailable previous years using the `fromMonth` prop, for restricting future months navigation we can use the `toMonth` prop, and pass in the current year and current month:
````javascript
  const currentYear = new Date(today.getFullYear());
  const currentMonth = new Date(today.getMonth());
  
  return (
    <>
      {/* <Styles range={range} /> */}
      <DayPicker
        // other existing props...
        fromMonth={new Date(2019, 12)} // this was from PR#1686 that restricts previous months where our data is not avail
        toMonth={new Date(currentYear, currentMonth)}
      />
    </>
  );
````
This will disable the forward triangle on the top right of the calendar when the calendar is on the current month.
<details><summary>screenshot no forward triangle</summary>
<p>

<img width="351" alt="Screenshot 2024-06-19 at 11 15 02 PM" src="https://github.com/hackforla/311-data/assets/69279538/9130eb46-643f-4571-a835-676b0c42e31d">


</p>
</details> 

---

### Disable the future day click events
There's also a built-in prop that disable days, which we've already use it to disable days after today:
````javascript
      <DayPicker
        disabledDays={{ before: lastThreeMonths, after: today }} // existing code
````
But for some reason React DayPicker created this prop to disable days only to be styled with CSS, the colors of disabled days just darkens, it does not disable click event 🤔. It allows you to define what days are disabled, but you need to DIY on what you want to do to these disabled days.

Luckily there is a simple one line solution for this. We already have a CSS modifier class that targets the disabled state of the `DayPicker-Day` element. Similar to what @aqandrew suggested, we can use `pointer-events: none` to achieve the disable mouse event behavior:

````javascipt
    /* Disabled cell */

    '& .DayPicker-Day--disabled': {        // existing styling line 50-55
      color: colors.textSecondaryDark,     // existing styling
      pointerEvents: 'none !important',   // <------ add pointer-events: none
    },
````
This will disable the future days remaining in the current month from being clickable.

Reference: [React DayPicker Docs](https://react-day-picker-v7.netlify.app/api/DayPicker), [MDN pointer events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)

2024-06-20 14:48 UTC, bphan002 commented
@aqandrew Thanks for pointing out that this shifts the layout and is disruptive. @Skydodle thanks for clarifying why the disabledDays prop needed css logic in order to work.  I was trying to figure out why the prop wasn't enough when I was working on it.

I think this is sufficient unless the design team wants to implement an error message for this issue. 

Thank you!

2024-06-20 16:07 UTC, aqandrew requested changes
Looking good. I left a comment with just one small change requested, because it's good practice to avoid `!important` where possible

2024-06-20 16:07 UTC, aqandrew commented on components/common/ReactDayPicker/ReactDayPicker.jsx
> +      pointerEvents: 'none !important',
```suggestion
      pointerEvents: 'none',
```

Pretty sweet that resolving this issue boils down to just a single CSS rule! `!important` isn't necessary here though; nothing else sets `pointer-events` on this element

2024-06-20 16:15 UTC, aqandrew approved these changes

2024-06-20 16:16 UTC, Skydodle requested changes
@bphan002 I would also disable forward month navigation beyond the current month. This would eliminate any confusion for the users in addition to disabling click event for days. There is no reason to provide users the ability to navigate to future months when they can't click on the days.

2024-06-21 01:00 UTC, bphan002 commented
Good catch,  I went ahead and did that as well.

2024-06-21 02:15 UTC, Skydodle approved these changes
Tested with no issues. No month navigation beyond current month, and no click event available for future days. Thanks @bphan002 !

2024-06-21 02:43 UTC, merged