add basic frontend tests with Vitest + React Testing Library
hackforla/311-data pull request #1873
Opened 2024-12-06 22:46 UTC by aqandrew

closes #1334

  - [x] Up to date with `main` branch
  - [x] Branch name follows [guidelines](https://github.com/hackforla/311-data/blob/master/GETTING_STARTED.md#feature-branching)
  - [ ] All PR Status checks are successful
  - [ ] Peer reviewed and approved

## Overview

- installs Vitest and React Testing Library to run frontend tests
- updates README to include instructions for running frontend tests
- adds example unit test utils.test.js + example UI test FilterMenu.test.jsx
- updates contributing.md re: writing tests

Note that this PR is missing one of the issue's action items; it does not set up a GitHub Action to block merging until tests pass. That effort should be part of a separate PR, and the example tests here are trivial enough that it won't hurt very much if we lack those status checks for some time.

Since I soon won't be available to contribute to this project further, I've braindumped some info about testing in contributing.md (for more objective info) and in this PR comment (for my opinions). I hope it's helpful! 🙏🏽

### On code coverage

Several of the issue's action items mention code coverage. IMO code coverage is a more helpful metric when testing backend code or a library. We should de-emphasize coverage when it comes to frontend testing, because testing all of an app's UI state is difficult to account for even with 100% frontend test coverage (citation needed).

### Additional resources

Both React Testing Library's and Redux's docs agree that the most valuable tests we can write are tests that most closely resemble how users interact with our software. These would be end-to-end (e2e) tests, which simulate complete user flows.

To write e2e tests, we need to work with the UX design team to define what all of our critical user flows are. For example,

>As a user, I want to export a CSV file for a certain request type in my neighborhood.

These definitions will help us determine what UIs/components we need to test, and what assertions we need to make about them.

e2e tests can be run with a tool like [Playwright](https://playwright.dev/), which is [recommended by Kent C. Dodds](https://kentcdodds.com/calls/03/02/would-you-recommend-to-use-playwright-or-cypress), creator of React Testing Library. But it's also possible to run comprehensive e2e tests with just Vitest and/or React Testing Library. A great example is [Excalidraw](https://github.com/excalidraw/excalidraw), an open-source React app whose UI is also primarily canvas-based. The challenge of testing canvas-based UIs is that UI tests make assertions about DOM node properties (whether an element is visible, what text it contains, etc.); however, canvas interactions generally don't update the `<canvas>` element. [Here's](https://github.com/excalidraw/excalidraw/blob/b5652b8e36abcc813478c65cdbe248aae774e5db/packages/excalidraw/tests/selection.test.tsx#L45-L78) one example of how Excalidraw makes assertions about app state--we could do something similar by making assertions about 311-Data's Redux store.

Excalidraw also has [GitHub Actions](https://github.com/excalidraw/excalidraw/blob/b5652b8e36abcc813478c65cdbe248aae774e5db/.github/workflows/test.yml) set up to run tests as status checks on PRs.

2024-12-06 22:52 UTC, aqandrew commented
Side note: I'm feeling very good about having taken the time to switch from Webpack to Vite in #1822 before opening this PR (thanks again @ryanfchase!). When I first started trying to add tests with Jest, Jest threw a lot of difficult-to-understand errors about CJS/ESM incompatibility. Vitest has no such complaints ✨

2025-01-27 19:54 UTC, ryanfchase requested changes
Requesting changes: there are a few failed tests when using `npm test`

2025-02-02 04:02 UTC, aqandrew commented
The failed test has been fixed in 2d58f3c. All tests pass when running `npm test`! 🥳

The failure was in FilterMenu.test.jsx, [while rendering FilterMenu](https://github.com/hackforla/311-data/pull/1873/files#diff-f5b38b9c582dbe92462145aea40012fada9101b5256b4dbe30fd558f6ae05012R8) which has a DatePicker as a child. In [DatePicker's `getCoordinates` function](https://github.com/hackforla/311-data/blob/8c43ecca1b6d036977d4a5cf4e2af7a85ff5c246/components/common/DatePicker/DatePicker.jsx#L129), `getClientRects` was returning an empty array, so I enabled falling back to `getBoundingClientRect` in that case.

2025-02-02 04:20 UTC, ryanfchase approved these changes
This PR is looking good. Tested locally and tests are passing. Approved, but asking @traycn to also review before we merge.

2025-02-15 19:39 UTC, ExperimentsInHonesty commented
Recorded to the cloud Tracys KT comments on 2025-02-15 :11:38

2025-02-19 02:45 UTC, merged